# Generated by Django 3.1.5 on 2021-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyfree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('students', models.IntegerField()),
                ('language', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
