# Generated by Django 3.1.5 on 2021-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyfree', '0006_auto_20210129_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
