# Generated by Django 3.1.5 on 2021-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyfree', '0007_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
