# Generated by Django 3.1.5 on 2021-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyfree', '0008_auto_20210129_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catelog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
