# Generated by Django 3.1.5 on 2021-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyfree', '0011_auto_20210131_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course',
            name='isActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(null=True),
        ),
    ]
