# Generated by Django 3.1.5 on 2021-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyfree', '0012_auto_20210131_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
